# Here we execute the tests and build the application

name: Build

on:
  push:
    branches: "afernandez-patch-3"
  pull_request:
    branches: "main"
  workflow_dispatch:
    input:
      tags:
        description: 'Tags to label this manual run (optional)'
        default: 'Manual run'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  test:
    name: Test Python ${{ matrix.python }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 40
    strategy:
      fail-fast: false
      max-parallel: 20 # Usage limits: https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration
      matrix:
        os: [ubuntu-22.04] # Available images: https://github.com/actions/runner-images/#available-images
        python: ['3.7', '3.8', '3.9', '3.10']

    steps:
    - name: Checkout
      uses: actions/checkout@v3 # Info: https://github.com/actions/checkout
    
    - name: Use Python ${{ matrix.python }}
      uses: actions/setup-python@v4 # Info: https://github.com/actions/setup-python
      with:
        python-version: ${{ matrix.python }}
    
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Python version and dependency list
      run: |
        echo "Python version expected: ${{ matrix.python }}"
        python --version
        which python
        pip list

    - name: Download dataset
      run: |
        python download.py

    - name: Run tests
      run: |
        pytest tests --disable-warnings --durations 0
