# Here we execute the tests and build the application

name: Build

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python3.10 -m ipykernel install --user --name python3.10
      - name: Download file
        run: python download.py
      - name: Run Tests
        run: python tests/test-notebooks.py
